name: YouTube Archive

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # cada 30 minutos

concurrency:
  group: youtube-archive
  cancel-in-progress: false

jobs:
  download-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -U yt-dlp
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Setup rclone config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Download videos
        run: |
          yt-dlp \
          --js-runtimes node \
          --cookies cookies.txt \
          --extractor-args "youtube:player_client=web;formats=missing_pot" \
          --download-archive archive.txt \
          --concurrent-fragments 5 \
          --retries 10 \
          --fragment-retries 10 \
          --no-overwrites \
          --merge-output-format mp4 \
          --embed-thumbnail \
          --add-metadata \
          -f "bestvideo[vcodec^=avc1][height<=1080]+bestaudio[acodec^=mp4a]/bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/bestvideo+bestaudio/best" \
          -o "%(uploader)s/%(upload_date>%Y-%m-%d)s/%(title)s.%(ext)s" \
          -a canales.txt

      - name: Upload to Google Drive
        run: |
          rclone move . gdrive:YouTubeArchive \
          --exclude ".git/**" \
          --exclude ".github/**" \
          --exclude "cookies.txt" \
          --exclude "canales.txt" \
          --exclude "archive.txt" \
          --progress
