name: youtube-archive

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install yt-dlp
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp

      - name: Install ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Create download folder
        run: mkdir downloads

      - name: Download videos
        run: |
          yt-dlp \
          --js-runtimes node \
          --remote-components ejs:github \
          --cookies cookies.txt \
          --ignore-errors \
          --download-archive archive.txt \
          --batch-file canales.txt \
          -f "bv*[height<=1080]+ba/b[height<=1080]" \
          --merge-output-format mp4 \
          -o "downloads/%(uploader)s/%(upload_date)s-%(title)s-%(id)s.%(ext)s"
